navigator:
  headless: false
  timeout: 30000
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"

llm:
  model_path: "models/Meta-Llama-3-8B-Instruct.Q4_K_M.gguf"
  context_window: 4096
  temperature: 0.1
  max_tokens: 1024

security:
  zap_path: ""
  scan_timeout: 300
  risk_threshold: "medium"